### ISSUE TITLE
User notification on suggestion approval/rejection

### ISSUE THREAD

**Issue by ldeluigi** [SpaceCowMedia/commander-spellbook-backend#223]
- would be great in the future), we'll want to probably provide a reason that it was rejected
- Also they could eventually be auto flagged as contributor since they are logging in through discord (cumbersome feature)

**Comment by GordonsKitchen** [comment]
We may want to have a general Notes field where we can note things about the submission. This can function as the way to give rejection reasons, but also for notes for accepted submissions. For example, if a user submits a combo that includes unnecessary card(s), we can make a note that we removed the unnecessary card. We could also note here variants that were accepted, if applicable.

**Comment by ldeluigi** [comment]
Today's discoveries:
* discord.py, pycord and interactions.py all lack support for a webhook only bot
* Discord, on the other hand, allows a bot to be [entirely based on wehbooks](https://discord.com/developers/docs/interactions/receiving-and-responding#receiving-an-interaction)
