### ISSUE TITLE
Incorrect parsing for mana prereqs imported from Google Sheet that start with text

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#234]
Many combos with variable mana costs are styled with a prerequisite in the form "At most {N} available."

The import to the backend incorrectly split these into two prerequisites: the 'other' prereq "At most.", and a mana prereq "{N} available." (Or "{N} [longer explanation].")

Many (but not all) of these combos were affected: https://commanderspellbook.com/search/?q=pre:"at%20most."

**Comment by ldeluigi** [comment]
@thirdpolice how bad would it be to fix those manually? We know how to filter for variants with "At most." in their prerequisites, I need to understand if I need to develop a script to automatically fix those in some way.

**Comment by thirdpolice** [comment]
I'm still hoping for a script solution, but let's continue to figure out the scale of the problem.

1) Prereqs in the form "At most {N} available." have been importaed as two prereqs, "At most." and "{N} available."

Your search found 103 affected variants.

2) Prereqs in the form "[Other words] "N} available." which have been imported as two prereqs, "[Other words.]" and "{N} available."

If you can put together a regex expression for me I can check this out in the Google Sheet. We'd be looking for prereqs where the { symbol appears without following ". " or "At most ".

3) Prereqs in the form "{N} available each extra turn." which have been imported as "{N} each extra turn available." due to the way the Mana Needed field is interpreted.

This likely affects 88 combos according to a frontend search. Presumably this requires a tech solution to allow Mana Needed to be parsed a different way.

----

Editing hundreds of combos manually would take up a lot of editor time, so I'm hoping for a script solution. If I do need to edit some of these manually, would it affect our URLs or cause any other problems if I redefined some of these Google Sheet variants as variants of the same combo? (That might save me editing time.)

**Comment by ldeluigi** [comment]
> I'm still hoping for a script solution, but let's continue to figure out the scale of the problem.
> 
> 1. Prereqs in the form "At most {N} available." have been importaed as two prereqs, "At most." and "{N} available."
> 
> Your search found 103 affected variants.
> 
> 2. Prereqs in the form "[Other words] "N} available." which have been imported as two prereqs, "[Other words.]" and "{N} available."
> 
> If you can put together a regex expression for me I can check this out in the Google Sheet. We'd be looking for prereqs where the { symbol appears without following ". " or "At most ".
> 
> 3. Prereqs in the form "{N} available each extra turn." which have been imported as "{N} each extra turn available." due to the way the Mana Needed field is interpreted.
> 
> This likely affects 88 combos according to a frontend search. Presumably this requires a tech solution to allow Mana Needed to be parsed a different way.
> 
> Editing hundreds of combos manually would take up a lot of editor time, so I'm hoping for a script solution. If I do need to edit some of these manually, would it affect our URLs or cause any other problems if I redefined some of these Google Sheet variants as variants of the same combo? (That might save me editing time.)

Ok I'll take care of this thanks

**Comment by ldeluigi** [comment]
Solved manually, thanks @thirdpolice
