### ISSUE TITLE
Unexpected change to capitalization

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#246]
Something strange I came across:

1. Variant 1173-1328-2160 had a mana needed field with "{1} each extra turn"
2. I saved its status as "Restore." (I made no other changes.)
3. I did some backend variant searches trying to find similar formatted combos, e.g. ' mana:"each extra turn" ' or ' pre:"each extra turn" ' and other variations, unsuccessfully.
4. I returned to that variant and the mana needed field was now capitalized: "{1} EACH EXTRA TURN"

I am not sure what caused this, let me know if you'd like me to try and reproduce it.

**Comment by ldeluigi** [comment]
It's a bug, thanks for spotting it. Back in the day when mana needed didn't allow english text it was safe to capitalize it. I'll fix it and remove capitalization.
