### ISSUE TITLE
Log entry incorrectly includes change to Description

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#249]
<img width="913" alt="Screenshot 2023-11-27 at 16 20 23" src="https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/8032571/8a65c474-d73a-4df6-8355-279932250445">

This log entry is inaccurate. The Status was changed, but the Description was untouched.

**Comment by ldeluigi** [comment]
It's caused by the fact that browsers use windows style `\r\n` new lines while in the database I imported unix style new lines `\n`.

I need to dig deeper to find how to make it consistent
