### ISSUE TITLE
Feature Request: URL preservation

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#254]
Current behavior as I understand it:
* A variant is defined by the cards it contains. If the cards need changing, the editor must delete that variant and create a new one.
* A variant page's URL is autogenerated and there is no way to manually change it.

Problem:
* Due to overlooked mistakes or changes in editing philosophy, editors sometimes need to add or remove a card in a variant.
* This will break all external URLs pointing to that combo page.

Possible solution:
* Add a variant status "Redirect" & the ability to point "Redirect" combos to another variant. This would set the old variant's page as a redirect to the new variant's page.

**Comment by ldeluigi** [comment]
Idea: Redirect table with the variant cemetery
