### ISSUE TITLE
Alerts appear on any freshly loaded page

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#269]
1. I saved changes to a combo
2. I immediately switched to the dependent variant tab and hit Refresh
3. The messages confirming my combo changes went through appeared on both the combo and variant page

<img width="1070" alt="Screenshot 2023-12-11 at 11 53 58" src="https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/8032571/6f8bdd12-61fa-4a5b-803d-69cc0a4b59d4">

Low priority, but good to address eventually so no one gets confused and edits a variant thinking it's a combo.

**Comment by ldeluigi** [comment]
Unfortunately this is completely out of my control as Django is responsible for that feature
