### ISSUE TITLE
Support queries on properties of cards in combos

### ISSUE THREAD

**Issue by crookedneighbor** [SpaceCowMedia/commander-spellbook-backend#276]
The main blocker for me right now is how we expose this in the search. 

Let's take card type for example. I don't think `type` as a search param makes sense, because it's not clear to me if `type` refers to the combo or to the card.

Possibly something explicit like:

```
cardtype:land
```

would find any combo that has at least one card that is a land and 

```
-cardtype:land
```

would find only combos that _do not_ contain a card with the land type.

Will need to come up with the kinds of card properties we're interested in supporting.

Ultimately, adding this before the database migration would bloat the JavaScript size a great deal, so we should probably hold off on this particular addition until after the Google Sheets -> database migration.

**Comment by ldeluigi** [comment]
Card properties in syntax that I'll add:
mana value
keywords
oracle_text
reserved
type_line

**Comment by ldeluigi** [comment]
926e281912442bd28b45fdccd8347f16dc91c6d1
