### ISSUE TITLE
Request: link from a Feature page to the Combos that produce it

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#318]
Maybe I'm missing something, but currently I'm using this awkward process:

1. Backend: find a nonstandard feature that needs correcting
2. Frontend: copy-paste this feature into the frontend search to find variants where it appears
3. Backend: search Combos one by one using the card names of each of these variants
4. Edit these combos and their variants to the standard wording of the feature

A link from a Feature page straight to a list of all the combos that produce it would cut out the need for the time-intensive steps 2 and 3.

**Comment by ldeluigi** [comment]
done in 668492edffca6c14526cb7bb660c0a7b1d26ec06
