### ISSUE TITLE
Feature sorting doesn't work

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#322]
Features are always sorted by ID descending, regardless of what sort options I've selected.

<img width="739" alt="Screenshot 2024-01-30 at 17 59 29" src="https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/8032571/8d1c80a3-b170-496e-aa76-4accc0a2e51a">

My browser and system info:
<img width="582" alt="Screenshot 2024-01-30 at 17 59 59" src="https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/8032571/987ccd2c-b151-4e2a-b9dc-7846ed506031">

**Comment by thirdpolice** [comment]
This is high priority, Astolfo can't start zir task until sorting features by name is possible.

**Comment by ldeluigi** [comment]
The numbers in the column indicate the priority in sorting. 1 for ID means it sorts by ID first

**Comment by ldeluigi** [comment]
Ok I see the bug
