### ISSUE TITLE
Duplicate Data on Combo / Variant Pages

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#329]
For some reason some variants duplicate all the data in the fields automatically. I did some sleuthing and it seems that it added the combo twice. Both combos have the same modification date and time. This is probably why the data was doubled. I'm not sure if there is supposed to be some form of duplicate protection to prevent this from happening that failed, or if there is some other quirk that caused this. Considering they have the same date and time of modification, it seems unlikely they were just added twice accidentally by the user (me).

Variant in question: https://backend.commanderspellbook.com/admin/spellbook/variant/2433-5365/change/?_changelist_filters=status__exact%3DN

![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/69d87200-303f-478e-add8-669d9ba5c416)
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/b862b732-bdbf-49e7-b438-68b20438af1c)
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/8482c124-d3f7-4291-9d73-33a65af2cd3b)
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/6b8d8647-f751-4613-a850-d41bec804ecc)

A note that I had a couple other variants in the past duplicate data like this in the steps. I don't remember what combos those were though.

**Comment by ldeluigi** [comment]
Weird, but there is no solution to this unfortunately. The backend can't tell when it's done on purpose or not.

You can detect some duplicates tho: https://backend.commanderspellbook.com/admin/spellbook/combo/?in_variants=overlapping
