### ISSUE TITLE
Identical duplicate combos

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#338]
I believe I misclicked when choosing features and accidentally made a combo that already existed on the site.

Could we add a check to prevent this, with a notice that the combo already exists?

![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/8032571/4261af3b-88fb-4e11-a7bf-fadbf366ef11)

**Comment by ldeluigi** [comment]
# TODO
- [ ] add a warning when saving a combo that is duplicate
- [ ] forbid setting a combo as generator if it's a duplicate

**Comment by ldeluigi** [comment]
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/44567586/8213e085-d780-41ee-9064-72cddbd24e3c)
