### ISSUE TITLE
Request: view feature cards on scryfall

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#339]
It would be useful to open a scryfall query that showed all the cards that produce a feature, in order to easily check while reviewing variants that no complications occur.

**Comment by ldeluigi** [comment]
Unfortunately scryfall allows at maximum 1024 characters in their query syntax, all those card names potentially could not fit and it would break.

As an alternative, I could show scryfall links in the list view of cards.

**Comment by ldeluigi** [comment]
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/44567586/785b4693-745a-4353-8da4-116f7fa6e2e0)

**Comment by ldeluigi** [comment]
Or else I could add a link that works only if all card names producing a feature fit into a scryfall query

**Comment by ldeluigi** [comment]
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/44567586/b3d15db1-9e69-4172-ac82-570a24fb431b)

**Comment by ldeluigi** [comment]
The link will appear only if the generated query is shorter than 1024 characters
