### ISSUE TITLE
[Enhancement] Allow Combo Search Bar to Search Names of Multiple Cards

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#343]
It would be nice if the search bar on the Combos tab could take the query and cross-reference it among _all_ the cards in the combo, instead of looking for one card with that query. This is very useful for easily being able to find a particular variant without needing to search through every single variant a card may have.

Example: I wanted to find combos using Xavier Sal and Intruder Alarm, so I searched "xavier intruder" and got 0 results:
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/5fa2bac6-2193-45fa-bc16-ddb950723a95)

Upon searching just "Xavier", I see the following (which I would like to see in the "xavier intruder" search):
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/2137988f-453e-4109-95c2-28aed5f8dfa5)

My assumption here is the program is looking for a card that has "Xavier" and "Intruder" in its name, rather than checking all the cards in a particular combo for a particular piece (like the front-end does). This would be very helpful if it could be changed.

**Comment by ldeluigi** [comment]
Try with `xavier + intruder`

Il Dom 10 Mar 2024, 02:03 Gordon ***@***.***> ha scritto:

**Comment by ldeluigi** [comment]
I'm adding explanatory text.
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/44567586/7185de10-5345-45a2-8182-c2ad0b9f960e)
