### ISSUE TITLE
Fix Headers for Cards in Features Tab

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#350]
I have a feeling the header here is not supposed to say "Card_features object". Also the number seems a bit arbitrary.

![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/7442119d-871e-4589-b024-12b00ba1ef3c)

**Comment by ldeluigi** [comment]
I know, but I can't easily hide it, unfortunately. The number is an identifier but has no purpose.
