### ISSUE TITLE
Translate Templates in Variant Suggestion to Utility Features When Possible

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#373]
The variant suggestions allow for users / editors to specify templates for generic effects (like a sac outlet). The problem with this is there is no way to specify utility features. For example, sac outlets are listed as utility features. So when we "Add as new combo", it doesn't find the utility feature and instead reads it as an unknown template. See the below pics:

![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/c7db931a-cba9-4352-a71c-750cb0150552)
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/19a84d16-a507-4f37-92e3-5375dd838f0f)

One of two ways to fix it.
1. Allow editors to add a specific utility feature to a variant suggestion, and then translate then when "Accept as new combo" is pressed.
2. Alter the program to search templates, and then search features for anything that matches the title. If it finds a feature, it can then add it. So if we put "Free Sacrifice Outlet - Creatures" in the Template field of a suggestion, the program would search for a template with that name. When it doesn't find it, it then searches for a Feature with that name. It would find it and then add it.

I have no preference on either of those options, so feel free to use your discretion on which is easier.

**Comment by ldeluigi** [comment]
I'm going with 2
