### ISSUE TITLE
Errors Cause Templates/Features to not be Deleted When Selected

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#379]
If an error occurs when saving a combo while a feature/template was selected to be deleted, that feature or template is not deleted, as the program unchecks the box to delete it.

Don't have a screenshot but you can repeat it by taking any combo, selecting to delete a template/required feature, and then causing another error to happen (usually by not having a zone selected for a card). You'll notice when it pops up again and throws the error that the delete box has been deselected.

**Comment by ldeluigi** [comment]
This is intended and is not a behavior I can change unfortunately
