### ISSUE TITLE
Updating Combo Doesn't Update Results for New/Restore Variants

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#396]
I updated a combo with some New/Restore variants, fixing a missing pre-requisite and adding a missing result. When I made the change, the program updated the variants with the new pre-requisite, but didn't add the new result. Maybe this is intentional behavior, but it seems a bit odd that it would make part of the changes and not all of them.

If this is something that can't be fixed to work in-place, it may be better to just automatically turn all variants into "Restore" to force them to be reloaded and the results added.

![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/27d1fc24-731f-4c4a-843b-e479c489f8e2)
Screen from the Combo page with "Infinite LTB" added.

![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/e052a04f-aa50-40da-88dd-babb89a22f11)
Screen from variant, no result

**Comment by ldeluigi** [comment]
This is intended.
Turning variants to restore would not help.

**Comment by ldeluigi** [comment]
The results are added in any case at the next generation

**Comment by ldeluigi** [comment]
Closing this because we agreed to only set related NEW variants to RESTORE status upon changes on combos
