### ISSUE TITLE
Accents Change Variant Suggestion Search Results

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#399]
When searching for a card that has an accent or other character in its name in the Variant Suggestions tab, it doesn't show if you don't have the accent. Since English keyboards don't have accents, it should be made to ignore those accents.

With accent:
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/a94c089c-f70a-4442-a102-0c0f52164ff1)

Without accent:
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/584049d7-e64b-420c-b21c-7b685f924aea)

**Comment by ldeluigi** [comment]
This problem only relates to variant suggestions
