### ISSUE TITLE
Automatic text replacement failed (because of special characters?)

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#404]
A few variants like this one https://commanderspellbook.com/combo/2054-2440-2714-5105/ were created using the automatic text replacement for this feature:

[[Permanent with "{2}: Add one mana of any color"]]

But this just shows up on the live site as that text, instead of the card that produces it.

A likely cause of the bug is that {2} is read as a graphics symbol.

**Comment by ldeluigi** [comment]
The issue was related with the ":" being used for aliases too. I'm fixing it by changing the alias character.
