### ISSUE TITLE
Request: Add CSB Card ID to Card page in backend

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#410]
I don't see the internal card ID anywhere on the card page. It would be mildly useful to access it from there for the purpose of quickly processing variant aliases when I've replaced one card with another.

**Comment by ldeluigi** [comment]
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/44567586/9d28747b-0ee8-443a-900f-47489a632353)

The id is in position **A**, in the URL.
Would you like to see it near B too?
