### ISSUE TITLE
Failed to generate a valid variant

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#412]
This combo existed on our site:
Experiment Kraj + Devoted Druid + Hardened Scales

In a single edit, I checked the "delete" box for Hardened Scales and added the more general "Increaser — +1/+1 counters" feature, then generated variants.

The Hardened Scale variant was not generated.

**Comment by ldeluigi** [comment]
It was generated with id 1323-2265-4762
