### ISSUE TITLE
[Autofill] Abbreviate Legendary Names at Comma

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#421]
Generally when a legendary creature name has a comma, we will negate everything from the comma onwards when writing the name in the combo. It would be nice if the autofill feature could do this automatically to save a bit of time.

For example, the card "Ulasht, the Hate Seed" would be abbreviated to "Ulasht" when put it via autocomplete. "The Master, Multiplied" would be abbreviated to just "The Master", and so forth. Basically the code can just check for a comma and discard everything from the comma onwards.

There are some very limited cases where we don't follow this convention, but we can fix those manually as those are very seldom to come by. Also note that I said "legendary names" in the title, but you don't need to check if the card is legendary. To my knowledge there aren't any nonlegendary cards that would have commas like this, so you can just check for a comma and truncate.

**Comment by ldeluigi** [comment]
How should it behave with DFC and modal cards? Should it always pick the first half of the name or should it leave the name unaltered and only apply the "comma" rule to non-split cards?

**Comment by GordonsKitchen** [comment]
I would say probably those can be unaltered, to be safe.
