### ISSUE TITLE
Negation of Mana Function in Query Shows Invalid

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#434]
The template function does not allow for negation with the keyword "mana".

See the photo below.
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/aba6e927-0dc1-478f-8883-f9f34f56228d)

Note the function only contains negation mana functions.

**Comment by ldeluigi** [comment]
The issue is with non caps lock mana symbols. It will be fixed in the next release
