### ISSUE TITLE
Combo not showing up in search

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#437]
(Combos will likely be edited by the time you see this, so behavior may have changed.)

Combo 9389 is Moritte of the Frost + Lesser Masticore + Phyrexian Altar.
Combo 9390 was Moritte of the Frost + Lesser Masticore + Ashnod's Altar, but I have just edited it to replace Ashnod's Altar with the utility feature Free Sacrifice Outlet - Creatures (Mana Only).

Variant generation has not been run yet, so each combo has only one associated variant, each one marked Restore.

Combo 9389 never shows up as a result for combo search. For example, "moritte + masticore" only returns 9390 and "moritte + altar" returns no results.

**Comment by thirdpolice** [comment]
I think I've figured it out: I was probably at a URL such as https://backend.commanderspellbook.com/admin/spellbook/combo/?variants__id=116-283-3908 and hadn't realized it.

It's pretty easy to make this mistake as my workflow involves multiple tabs and Opera doesn't even show anything in the URL from "?" onward. Is it possible to add an obvious visual cue near the top of the page that reminds the user that the whole database isn't being searched?

**Comment by ldeluigi** [comment]
I've added a visible text note in case the result list is filtered through something that is not visible from the rightside filter panel, such as variants_id=....

For instance:
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/44567586/9d16d01f-e9e4-4b8e-be8b-ba56d89ba002)
