### ISSUE TITLE
Starting card state from features erroneously added to variants that use that card by name

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#438]
https://backend.commanderspellbook.com/admin/spellbook/combo/9387

This combo has a blank field for Moritte of the Frost's starting card state.

But when variants were generated, each variant adds "as a copy of the planeswalker." to Morrite of the Frost's starting card state. This text is taken from Moritte's field the "Clone - Planeswalker" utility feature, but it should not appear here since that feature is not part of the combo.

**Comment by ldeluigi** [comment]
Leaving notes to myself for a solution to this problem:
Separate "included combos" into two different relationships:
* combos included in the requirement graph
* combos included in the results graph (these will implicitly include the first)

**Comment by thirdpolice** [comment]
This also occurs when a different feature with a blank starting state is used. E.g. a combo using feature 1771, "Clone - Creature (Bypass Legend Rule)" (which currently has a blank starting state field for Spark Double), will generate a Spark Double variant with that same "as a copy of the planeswalker" starting state text.

**Comment by ldeluigi** [comment]
9c07b1b380bc8eaef416992072ca523914508ebe
