### ISSUE TITLE
Override of Feature Zone Location

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#443]
There are some cases where being able to override the zone locations of a feature would be very helpful to reduce the amount of changing zones editors have to do. It would be nice if we could optionally set a zone for the feature, and if a zone is set, it will override whatever the feature specifies as the zone for each card. So if I choose the feature "Clone - Creature" and specify "Hand" as the zone, it will set "Hand" as the zone no matter what the feature would specify for each card.

Example Use Case: The combo "Wispweaver Angel + Clone - Creature -> [results]" requires the Clone to be in hand, but the default zone for the Clones is set as battlefield. So I need to go through and manually change every individual variant to say hand instead, where the override would save me having to do that.

If you can't make the zone specification optional, you could add an option like "Use default zone" which will apply the default zone set in the feature page for each card.

**Comment by ldeluigi** [comment]
@GordonsKitchen what if the feature is replaced by multiple cards because it is produced by an utility combo? Should I put the override on every card needed?

**Comment by GordonsKitchen** [comment]
I would say yes in that case. There are going to be cases where that isn't ideal, but not doing it also causes the same issue. Let's take two Clones for an example, one in hand and one on BF

If you override to hand, you have to change half of them to BF. But if you don't override (the default for Clones is BF), then you have to change half to hand anyways. So I think that behavior is fine.
