### ISSUE TITLE
Add User Setting to Receive Changelog Notifications

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#451]
It would be good to add an option in the User pages where we can specify whether a particular user will receive a ping in the Discord _changelog_ channel when their suggestions are accepted and/or rejected. I would suggest naming the option "Receive Discord Notifications" as a toggle checkbox with a message basically saying "This sets whether the user will receive Discord ping notifications when their submissions are accepted or rejected" below the box. Checked means the user will get pinged whenever their suggestion is processed, unchecked means they won't. The default should be checked in this case.

You can either not send a webhook at all should the box be unchecked, or you can send it _without_ the direct ping, whichever you prefer. While users don't have direct access to this setting yet, I would envision we would implement such things at a later date when we (hopefully) get to user quests, and allowing users to view their submissions. Then we could make an Account Settings tab where they can change this parameter if desired. We can also do it manually if someone requests it before then. I would use this for myself because I don't need notification that my submissions have been accepted when I'm the one accepting them.

**Comment by ldeluigi** [comment]
I can't change the user page but I can create a sort of "UserSettings" companion page linked to the user that contains anything we want

**Comment by ldeluigi** [comment]
@GordonsKitchen why, as an editor, are you using suggestions to prepare new combos? Isn't DRAFT combos suitable for your usecase? Those don't send notifications at all

**Comment by GordonsKitchen** [comment]
The reason I use suggestions is so there's a trail and credit for when we eventually have that down the line. We've talked in the past about having lists of submissions that users can view, as well as some form of point / EXP system related to that. If this is going to be a pain for you to fix you can just ignore it, it's probably an issue that only affects me for now. But it would be good later on when/if users get more account control to toggle the setting.

**Comment by ldeluigi** [comment]
I can fix it easily with one of these compromises:
* I can skip notifying someone if it's the same user that accepted the combo
* I can skip notifying someone if it's allowed to accept suggestions in general, thus implying that probably it's an editor

**Comment by GordonsKitchen** [comment]
I'd say the first option is the best. If another editor accepts my submission, I would still want to be notified so that I know it was accepted. Obviously, if I accept my own submission, I know it has been accepted and don't need a second notification of that
