### ISSUE TITLE
Exclude templates from the singleton restriction

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#454]
It doesn't appear combos with a template whose quantity is 2+ are generating variants.

The combo https://backend.commanderspellbook.com/admin/spellbook/combo/27374/change/?_changelist_filters=q%3Dbhaal%2B%252B%2Bpersist does not generate the variant to OK and put on the site.

You can check: https://backend.commanderspellbook.com/admin/spellbook/variant/?q=bhaal and see that it isn't listed there under any status level.

**Comment by ldeluigi** [comment]
This is intended for combos who don't have `allow_multiple_cards` enabled. I've changed the issue to a feature suggestion to make templates "special" bypassing any singleton restriction
