### ISSUE TITLE
Add starting prerequisites field to "produced by cards" section of features

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#463]
We already have a "battlefield starting card state" field, which alters the starting zone prereq, but many cards have their own, separate prerequisites in order to fulfill a feature. It would be great if editors could write those prereqs once in the feature tool and have it autopopulate to new variants.

For example, this "Creature that taps for 4+ green" feature is full of cards that require a certain amount of life or power or creatures or elves etc., making combo generation with this feature quite tedious: https://backend.commanderspellbook.com/admin/spellbook/feature/1938/

**Comment by ldeluigi** [comment]
Use combos for that, it's their purpose

**Comment by thirdpolice** [comment]
I ran a test just now:

Creating three utility combos took me between 28 seconds and 1 minute 34 seconds each.

Typing the same prerequisites into a feature text field took me between 5 seconds and 18 seconds each.

This would be a game-changing time save when multiplied by the hundreds of times we need to do this.

**Comment by ldeluigi** [comment]
I'll consider it, thanks for the feedback.
