### ISSUE TITLE
Missing results from utility feature combo

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#468]
I've just created https://commanderspellbook.com/combo/708-997-2459-4753/ by generating variants from a single combo.

I noticed it didn't include the result "Near-infinite scry 1" which should be added automatically due to the utility combo https://backend.commanderspellbook.com/admin/spellbook/combo/26336 

I ran a sitewide variant generation job but that didn't fix the issue.

A similar problem exists for the older variant (from a different combo) https://commanderspellbook.com/combo/708-2292-2459-2500/

I can't find anything wrong with the backend setup:
![Screenshot 2024-07-02 at 19 49 48](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/8032571/197491d2-fdc7-4491-a2b8-ddc3d380d035)

**Comment by ldeluigi** [comment]
Take a look at https://backend.commanderspellbook.com/admin/spellbook/combo/26876/change/ in particular the REMOVED FEATURES

**Comment by thirdpolice** [comment]
Thanks, I got a bit of tunnel vision there…On 3 Jul 2024, at 21.30, ldeluigi ***@***.***> wrote:﻿
Take a look at https://backend.commanderspellbook.com/admin/spellbook/combo/26876/change/ in particular the REMOVED FEATURES
