### ISSUE TITLE
Variant alias not created for template change

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#469]
I edited https://commanderspellbook.com/combo/1940-2882-4128-4662--1/ to use a template instead of a prereq, but I noteice that no variant alias was created.

**Comment by ldeluigi** [comment]
Variant aliases are generated when a variant is deleted.
A variant can only be deleted with a full variant generation, but you only ran generations relative to single combos, thus the old variant without the template is still there, and no variant alias for that has been created.
