### ISSUE TITLE
"Delete" in attribute field deletes all attributes

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#483]
Desired behavior: Pressing delete in the feature attribute field should only delete a single attribute, not all of them.

**Comment by ldeluigi** [comment]
This deletes one of them:
![image](https://github.com/user-attachments/assets/00f638bb-1247-4b2d-8b86-ff573d3b452a)

This deletes all of them:
![image](https://github.com/user-attachments/assets/6ed7bd81-bab1-47b6-8b65-630fe016bc2b)

**Comment by thirdpolice** [comment]
I meant the "backspace" key on the keyboard.

<img width="279" alt="Screenshot 2024-07-20 at 22 09 49" src="https://github.com/user-attachments/assets/67e576b5-3467-455e-a9ec-6b6c3c73b27b">

After pressing backspace:
<img width="270" alt="Screenshot 2024-07-20 at 22 11 48" src="https://github.com/user-attachments/assets/9f07575f-2c20-4b3f-99a9-1d8bc45009a0">

On further testing, if I click outside the field, then click to return to that field, then press backspace, it instead undoes the last attribute selection, making it editable text instead:

<img width="291" alt="Screenshot 2024-07-20 at 22 10 51" src="https://github.com/user-attachments/assets/94272b9e-1e25-4956-9bed-be69b821f7b1">

**Comment by ldeluigi** [comment]
Related to https://github.com/select2/select2/issues/3335
