### ISSUE TITLE
Variants were generated with no text & incorrect zone

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#486]
I generated variants for a single combo, https://backend.commanderspellbook.com/admin/spellbook/combo/27664/ , and its variants ( https://backend.commanderspellbook.com/admin/spellbook/variant/?of__id=27664 ) were generated with no text in any fields.

These variants also specify "Battlefield" for Dualcaster Mage despite that card's starting location "Hand" in the combo.

**Comment by ldeluigi** [comment]
The issue comes from the fact that the combo does not have explicit results, thus being considered "unused" by the generator and thus its text fields are getting ignored. I'm adding a special case handler to force generator combos to be considered useful regardless.

**Comment by thirdpolice** [comment]
Thanks, Deloo. That is my bad; it should have results. Maybe there is some corner case where we'd want a results-less combo but it hasn't happened yet.
