### ISSUE TITLE
Sorting Not Resetting when Sort Parameters are Cleared

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#534]
I noticed this on the "Variants" page but it may apply to other pages. When you apply a sort (such as Name Ascending) and then clear the sort, the sorting does not revert to the default sort you see when you open the page.

Original, no sort parameters:
![image](https://github.com/user-attachments/assets/6ee3bd24-aba5-43c4-a565-2380ad578d2c)

Sort applied:
![image](https://github.com/user-attachments/assets/20d0b89f-6316-480f-9dc7-256c4a3a6ac7)

Sort cleared (using the left button shown above)
![image](https://github.com/user-attachments/assets/4ff92290-0757-403a-95fb-ec40446db173)
This is the same as when the sort was applied, even with no sort.

**Comment by ldeluigi** [comment]
I've done some reseearch and I found out that this is the behaviour of the framework we are using, Django, and not something I can easily overwrite in such a way that's worth. So, just be aware that if the page url on top of your browser contains a `o=` query parameter, that means that the default ordering is skipped, and results are shown without ordering. You need to manually remove the `o=` parameter or click on the Variants page again to reset to the default ordering.

In the meantime, I also noticed that ordering by variant name did not work at all, and I should have fixed that issue in the next release.

We can consider opening a ticket on Django to better understand why that is the intended behavior.

**Comment by ldeluigi** [comment]
Relevant ticket: https://code.djangoproject.com/ticket/35747
