### ISSUE TITLE
Add Way to Add 2+ Feature Pieces with Differing Attributes

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#546]
I was working on condensing all the previous "Free Sacrifice Outlet" (hereafter referred to as FSO) features into one feature using attributes. I came across a combo, however, that I cannot condense using the current system. What I was doing was taking all the type-specific features (like FSO - Creatures, FSO - Artifacts, FSO - Lands and etc.) into one FSO feature, and using attributes to specify what is needed to be sacrificed. So FSO with the "affects-creature" attribute mirrors the former FSO - Creatures feature, and so on for all the remaining FSO features. With this is mind, look at the below combo

![image](https://github.com/user-attachments/assets/4681503e-648c-42b0-a28b-483d3ac4a9fb)

This combo requires a FSO for both a creature and an enchantment. There is no way under the current system to readily do this. I could make both "affects-creature" and "affects-enchantment" in the Any sections and then manually view them to grab the ones that generated a creature and an enchantment sac outlet. This, of course, is time consuming and not exactly ideal from a time standpoint. 

So, with this is mind, it would be ideal to be able to specify a feature with quantity 2+, and split the attributes. I have some ideas for this:
1. Allow us to specify a feature more than once. So in the above example I would have [FSO with attribute: affects-creature] as one feature, and then [FSO with attribute: affects-enchantment] as a separate feature. This causes issues with name shortcuts (in double brackets) since both features have the same name.
2. Allow us to "split" a feature with quantity 2+ to specify varying attributes. So I would specify FSO once with quantity 2, and then split the attributes. Card 1 could have the "affects-creature" attribute, and Card 2 could have the "affects-enchantment" attribute. It would need to be ensured that each card is only pulling from their attributes. There's a naming issue here which exists with quantity 2+ anyways that I will address in a separate GH issue (see #547)

**Comment by ldeluigi** [comment]
done!
