### ISSUE TITLE
Naming for Features with Quantity 2+

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#547]
Currently if we specify a quantity of 2+ for a feature, the naming shortcuts (like [[text]]) cannot differentiate between the two separate cards included in the feature generation. It would be good to make it so we can specify a particular card in the feature to save time. The way I thought of it working was specifying the specific card via numbers. So let's assume feature A is listed with a quantity of 2, we could use [[A%1]] to denote the first card pulled from feature A, [[A%2]] for the second, and so forth. The % can be any special character you see fit, except a dash (-), equal (=) or plus (+) because we commonly use those in feature names. Whatever character is chosen, it would be advisable to then edit feature names and template names to forbid that character. I would recommend maybe the tilde since it seems to make sense and is something we won't use, but realistically any special character except those mentioned should work fine.

Mentioned in #546

**Comment by ldeluigi** [comment]
I've implmented `[[Feature X|Alias1$2|Alias2]]` with `Alias1` as a new alias for `Feature X`,, `2` as selector for the second replacement for `Feature X`, `Alias2` as a new alias for the second replacement of `Feature X`
