### ISSUE TITLE
Add Filters to Card Page for Initial Release Year / Set

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#563]
I had the idea to do an end-of-year recap article where I could look at the best combo cards released this year. In order to do this, I need the backend to sort the cards I give them based off a release year, to easily tell what cards were released when. Two ways to do this:

1. Specify a year, and the backend pulls all cards whose initial release was that year. So "2024" will return any card whose initial release date has the year 2024.
2. Specify set(s), and the backend pulls all cards whose initial release was in that set. This is an alternative option where I could just chain-add sets to make the 2024 list if doing the year isn't feasible.

If possible, adding both would be nice. I would strongly prefer to just put in a year, but if that isn't feasible or very difficult, then specifying sets would be OK.

I would need this by no later than December 1st, 2024. I plan to release these articles in mid-late December, right before the new year.

**Comment by ldeluigi** [comment]
We agreed on a one-time script as a solution instead of a new feature
