### ISSUE TITLE
Filtering for Feature Attributes Sometimes Shows Extra Results

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#581]
Sometime when searching for a feature attribute, you get extra results that are not expected. See the two images below

![image](https://github.com/user-attachments/assets/fa794407-94a9-41ad-931b-efa4a932c059)

![image](https://github.com/user-attachments/assets/ce328633-7ea8-46b1-af69-ebe414b449eb)

As you can see, the top searching for "taps for R" brings up a bunch of different results. I'm guessing this is because "for" has an R in it. Whereas the bottom, "taps for W" only pulls that attribute, as expected.

**Comment by ldeluigi** [comment]
You are supposed to use quotes to make your query stricter:
![image](https://github.com/user-attachments/assets/0cfcbd16-b32a-48fe-b5f6-847a0da73ed3)
