### ISSUE TITLE
Set Variants from a Deleted Combo Automatically to Restore

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#612]
When a host combo is deleted, it would be good if all variants tied directly to that combo were automatically set to "Restore". This is useful when editors are condensing combos into one combo using features, so that the changes made to the new combo are automatically applied without needing to manually set them to Restore. If there is concerns about unintended restores, there could also be another option added to do this. So an option for "Delete selected combos" and one for "Delete selected combos and restore produced variants" to allow more control.

**Comment by ldeluigi** [comment]
Maybe I can set to restore only the variants that were generated only by the deleted combo and not others

**Comment by GordonsKitchen** [comment]
Yes that was my intention. Only variants that have the deleted combo as their parent (i.e. were generated from that combo) would be marked as restore. Any that include the combo, but were not generated from it, will be unaffected.
